# Generated by Django 5.0 on 2024-01-03 00:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_proyecto', models.CharField(max_length=200)),
                ('descripcion_proyecto', models.TextField(blank=True)),
                ('fecha_proyecto', models.DateTimeField(null=True)),
                ('cod_licitacion', models.CharField(max_length=50)),
                ('tipo_licitacion', models.CharField(choices=[('Pub', 'Público'), ('Pri', 'Privado')], max_length=3)),
                ('tipo_construccion', models.CharField(max_length=100)),
                ('precio_1', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('fecha_precio_1', models.DateTimeField(null=True)),
                ('precio_2', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('fecha_precio_2', models.DateTimeField(null=True)),
                ('precio_3', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('fecha_precio_3', models.DateTimeField(null=True)),
                ('enlace', models.URLField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_modifico', models.DateTimeField(null=True)),
                ('usuario_modifico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizaciones_modificadas', to=settings.AUTH_USER_MODEL)),
                ('usuario_registro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizaciones_registradas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
